.gitignore
openai/api_resources/__init__.py
openai/api_resources/fine_tune.py
openai/cli.py
openai/version.py
setup.py

Fine-tuning is a closed beta feature. For access, please [submit your information here](https://docs.google.com/forms/d/e/1FAIpQLSdhUQN_r43xsnYPwLvAl6unLVyCsaXW-3oh7VzJY7FaqaM6zA/viewform)
Future changes to the /fine-tuning api will be registered as patch-level version bumps while it is in closed beta.

Add /fine-tunes closed beta endpoint to the CLI

---

openai/api_resources/abstract/engine_api_resource.py
openai/api_resources/completion.py
openai/cli.py
openai/version.py

This PR does several things:
- Support engineless completions in the SDK/CLI. (Context: `/v1/completions` is now a thing. If the `engine` parameter is not supplied, we make requests to that path. Otherwise, if `engine` is provided, requests are made to `/v1/engine/<ENGINE>/completions`. We expect most users to still use `engine` right now.)
- A few cosmetic improvements
- Undocuments the timeout parameter on completions

Support model-based (/engineless) completions in openai cli

---

openai/cli.py
openai/validators.py
openai/version.py

From
```
git cherry-pick 599819d 731df35 605c590
```

Cli fixes and improvements

---

openai/validators.py
openai/version.py

* ensure that only a single whitespace is prepended. Ensure the message regarding the prompt separator is displayed only if a prompt separator exists.
* change pandas contains to not use regex, which can trip if the common_suffix is actually a regex

Minor fixes to tools (prepare_data validators)

---

openai/cli.py

Edited line 597 to match condition in line 242, "classifications". Also edited line 243 to match documentation ("label", not "labels").
With these changes `openai tools classifications.prepare_data -f <FILENAME>` works to convert files to JSONL.

Fix CLI tool for generating JSONL for classifications

---

openai/api_requestor.py

These were passed as positional arguments, but in the wrong position, which meant they were passed into [the `json_body` parameter](https://github.com/openai/openai-python/blob/62f8d40ffc6d3a723f5f1d99fee7febfd47026b5/openai/error.py#L10) of the `OpenAIError` constructor.

Fix recording of reponse headers in exceptions.

---

openai/wandb_logger.py

Fixes issue where we tried to access a results file even when finetune status was not "succeeded"

fix(wandb): no results if not succeeded

---

.isort.cfg
openai/__init__.py
openai/api_requestor.py
openai/api_resources/abstract/api_resource.py
openai/api_resources/abstract/engine_api_resource.py
openai/api_resources/engine.py
openai/cli.py
openai/error.py
openai/openai_object.py
openai/tests/test_api_requestor.py
openai/tests/test_url_composition.py
openai/util.py
pyproject.toml
setup.py

[lint] standardize isort and black in pyproject.toml

---

openai/wandb_logger.py

Datasets are saved as wandb artifacts using original file names.
However, some characters are not allowed to be used as artifact name.
This PR sanitizes the name used as wandb artifact.
It also ensures results are present even when a run is marked as `succeeded`.

feat(wandb): sanitize name

---

openai/api_requestor.py

Fix reusing of HTTP Connection
`return` while reading lines will close Generator and cause `GeneratorExit` exception, that will close connection & socket
In this case system will produce TCP RST packet.
Closes https://github.com/openai/openai-python/issues/95

Fix http reuse connections

---

openai/api_requestor.py
openai/api_resources/error_object.py

Fixed args in refresh_from call in ErrorObject

---

openai/api_resources/moderation.py

Fixes https://github.com/openai/openai-python/issues/122
This PR enables making moderation endpoint calls without setting API key as environment variable or binding API key to `openai` module globally.

Add api_key parameter to Moderation.create

---

openai/tests/test_long_examples_validator.py
openai/tests/test_prepare_data.py
openai/validators.py

KeyError occurs when running `openai tools fine_tunes.prepare_data -f training_file.jsonl` when `training_file.jsonl` contains a prompt/completion that is BOTH a duplicate and a long example. Without trying to change too much, this fix would:
- wrap the retrieval of `long_examples` and `long_indexes` into a function, calling it preemptively within `long_examples_validator` to provide analysis information about how many rows are long examples, then calling it when actually dropping rows within `optional_fn` and providing info to the user if the keys that are being dropped have changed. 
Fixes #121 
I am also happy to provide a file that can be used to reproduce this error.
When the error would normally occur, instead you would see:
```
❯ openai tools fine_tunes.prepare_data -f …
```

Fix KeyError occurring using fine_tunes.prepare_data

---

README.md

* Add Moderation endpoint to readme
* add basic example

Add Moderation endpoint to readme (#151)

---

openai/wandb_logger.py

Default encoding on Windows is not `utf-8` which creates issues with the fine-tunes.
Updated artifact encoding and forced it to correct formatting.
fix #143

fix(wandb): encoding on Windows

---

setup.py

Currently, there is no 'long' description of the project, i.e., the project page on pypi is empty.
This PR uses the content of the `README.md` as long description.

Include long description

---

openai/api_requestor.py
setup.py

typing_extensions are only used for Literal which is available in the standard library since Python 3.8

Do not require typing_extensions with Python 3.8+

---

README.md
openai/__init__.py

* Set default azure `api_version` to `2022-12-01`
* Remove search example from README because search is not longer supported
* Changed token authority (see https://github.com/openai/openai-cookbook/commit/3c334e70ddd3f7b9e63e1136bb583d02bd8127bc)

Azure OpenAI 2022-12-01

---

README.md
openai/__init__.py
openai/api_requestor.py
openai/api_resources/abstract/api_resource.py
openai/api_resources/abstract/createable_api_resource.py
openai/api_resources/abstract/deletable_api_resource.py
openai/api_resources/abstract/engine_api_resource.py
openai/api_resources/abstract/listable_api_resource.py
openai/api_resources/abstract/nested_resource_class_methods.py
openai/api_resources/abstract/updateable_api_resource.py
openai/api_resources/answer.py
openai/api_resources/classification.py
openai/api_resources/completion.py
openai/api_resources/customer.py
openai/api_resources/deployment.py
openai/api_resources/edit.py
openai/api_resources/embedding.py
openai/api_resources/engine.py
openai/api_resources/file.py
openai/api_resources/fine_tune.py
openai/api_resources/image.py
openai/api_resources/moderation.py
openai/api_resources/search.py
openai/cli.py
openai/embeddings_utils.py
openai/openai_object.py
openai/tests/asyncio/test_endpoints.py
openai/tests/test_long_examples_validator.py
setup.py

Fixes #98 
Adds asyncio support for API. Does not support CLI (does not make sense).
I haven't tested file upload. aiohttp does not include the files parameter like requests, so I'm using requests' private utility function in the ApiRequestor
Usage (notice the `a` prefix, used in CPython lib, Django, and other libs):
```python
import openai
openai.api_key = "sk-..."
async def main():
await openai.Completion.acreate(prompt="This is a test", engine="text-ada-001")
```
Installation of aiohttp can include speedups that aren't included in setup.py. aiohttp is a required package, but it doesn't have to be. We'd just need to remove the typing.

Add async support

---

openai/api_requestor.py
openai/api_resources/file.py

When a global session wasn't set in `openai.aiosession`, we would create a temp `ClientSession` on the fly. Unfortunately, this session wasn't scoped correctly since it was closed upon returning from `arequest_raw` but `_interpret_async_response` would later call `await result.read()` on the response, which would hang since the backing session had already been closed.
This patch ensures that the session is kept open for the duration of the request *and* the entire parsing of the response.

Fix API requestor hanging when not using a global session

---

README.md
openai/api_resources/embedding.py
openai/datalib.py
openai/embeddings_utils.py
openai/tests/test_long_examples_validator.py
openai/validators.py
openai/wandb_logger.py
setup.py

This PR makes data libraries like `numpy` and `pandas` optional dependencies. These libraries add up to 146MB, which makes it challenging to deploy applications using this library in environments with code size constraints, such as AWS Lambda.
Since the primary use case of this library (talking to the OpenAI API) doesn’t generally require data libraries, it’s safe to make them optional. The rare case when the data libraries are needed in the API client is handled through assertions with instructive error messages. 
Installing `openai-python` requires the `numpy`, `pandas`, and `openpyxl` data libraries that add up to 146MB:
```bash
$ pip install -e .
$ du -sh $VIRTUAL_ENV/lib/python*/site-packages/
167M	/Users/jakub/.virtualenvs/openai-python/lib/python3.11/site-packages/
```
Installing …

Make `numpy` and `pandas` optional for ~7 times smaller deps

---

openai/api_resources/image.py
openai/cli.py

* Add optional mask for dalle's edit api

Add optional mask for dalle's edit api (#157)

---

openai/api_resources/fine_tune.py

We incorrectly changed the original method to be async rather than making a new async version. This PR fixes that.
Fixes #173.

Fix `FineTune.stream_events`

---

openai/api_requestor.py
openai/api_resources/abstract/engine_api_resource.py
openai/tests/asyncio/test_endpoints.py

#171 
Note that as per the issue above, even after the two fixes below this test still fails, as the 2nd chunk of the stream never arrives

Several fixes to make `Completion.acreate(stream=True)` work

---

openai/api_requestor.py
openai/tests/asyncio/test_endpoints.py

There were a bunch of mypy issues when I applied this internally so fixing them here.
Also deal with async stream line parsing a bit more robustly (iterating over an `aiohttp.StreamReader` by chunks could still return multiple lines so let's keep using the regular one and deal with multiple lines separately).
Finally make sure that we correctly close the underlying session if an exception is raised while we're making the raw request.

Fix some typing issues

---

openai/cli.py

* Adds a `fine_tunes.delete -i <ID>`  command to delete fine-tunes using the CLI

[Azure] Add fine_tunes.delete CLI command

---

openai/api_resources/file.py

Fixes https://github.com/openai/openai-python/issues/196, and probably https://github.com/openai/openai-python/pull/185 and https://github.com/openai/openai-python/pull/183
This MR reverts the change in https://github.com/openai/openai-python/pull/146/files#r1084884786 so that the requests hit the `/content` url of the api again.
cc @Andrew-Chen-Wang @ddeville 
To reproduce, on the older openai==0.25.0
`
```
openai api fine_tunes.results -i <job_id_here>
```
You'll get the output of the actual CSV file
E.g.
step,elapsed_tokens,elapsed_examples,training_loss,training_sequence_accuracy,training_token_accuracy
1,22048,32,0.011019098009307718,0.0,0.0
1,32288,32,0.007613447834811513,0.0,0.0
On the current openai==0.26.2
You get instead
{
"object": "file",
"id": "file-66NnpqAXzw3In27fROPIU03P", …

fix(download): Fix download url by reverting change

---

pyproject.toml

Add license metadata for pypi.
Please see the documentation at:
https://packaging.python.org/en/latest/specifications/declaring-project-metadata/?highlight=license
Having this would make it easier to use this package in a corporate environment where python package licenses need to be approved.

Add license metadata for pypi

---

openai/api_resources/customer.py
openai/api_resources/moderation.py

This PR updates the code to use "cls" as the first argument for class methods for improved readability and consistency with community conventions.

Replace self with cls in classmethods for consistency

---

openai/api_resources/file.py

`File.__find_matching_files()` can't correctly detect matching files because of missing file size info. It compares remote file size with the `bytes` builtin.
Regression: 0abf64137c18b45925d5015bae80429adb46fac6.
This PR adds `bytes` argument to the `File.__find_matching_files()`.
PS: Better to rename `bytes -> bytes_` to not shadow builtin name and prevent such issues in the future.

Fix File.find_matching_files()

---

openai/api_requestor.py

I was able to reproduce #184 where sometimes calling `Completion.acreate(stream=True)` would result in a JSON parsing issue. 
This was happening because our code was trying to parse incomplete JSON objects. It was receiving chunks that looked like this (notice the incomplete line at the end):
```
data: {"id": "cmpl-6hDMH0KtbEmSdkAvX4xEHy7be8XMz", "object": "text_completion", "created": 1675757473, "choices": [{"text": "\\n", "index": 0, "logprobs": null, "finish_details": null}], "model": "text-davinci-003"}\n\ndata: {"id": "cmpl-6hDMH0KtbEmSdkAvX4xEHy7be8XMz", "object": "text_completion", "created": 1675757473, "choices": [{"text": "Hello", "index": 0, "logprobs": null, "finish_details": null, "model": "text-davinci-003"}\n\ndata: {"id": "cmpl-6hDMH0KtbEmSdkAvX4xEHy7be8XMz", "object": …
```

Fixes #184: JSON parsing issue when async streaming

---

setup.cfg

I noticed sklearn is in the install which is deprecated and scikit-learn is already in there as well, and scipy was missing.
This fixes #210

Fixes for embedding requirements install

---

openai/api_resources/abstract/api_resource.py

Related to https://github.com/openai/openai-python/issues/231
When Completion is incorrectly used, the error suggests an bug in the codebase:
```
openai.api_key = "openai-key"
id_ = "cmpl-id"
result = openai.Completion.retrieve(id_chat)
```
With kwargs used, the params are passed correctly and a clearer error is thrown:
```
```

Use kwargs

---

examples/codex/backtranslation.py

Updated `Backtranslation_of_SQL_queries.py` to match the conventions of the other examples files that point to https://github.com/openai/openai-cookbook.

Improve consistency of the SQL example pointer

---

README.md

Source:
https://github.com/openai/openai-python/blob/main/openai/error.py#L79-L80

Update README.md openai.error.TimeoutError -> openai.error.Timeout

---

README.md
openai/__init__.py

Chat completions on Azure have been released to the public under a preview version '2023-03-15-preview': [Reference](https://techcommunity.microsoft.com/t5/ai-cognitive-services-blog/working-with-gpt-4-and-chatgpt-models-on-azure-preview/ba-p/3773595)
Thus we would like to have this preview version as the default.

[Azure] Version '2023-03-15-preview' as default

---

openai/error.py

`api_requestor.py` recently started respecting `text/plain` response `Content-Type`s. Azure OpenAI can sometimes return errors with that Content-Type that are still JSON strings with error info, which can break OpenAIErrors default behavior of checking for `error` being `in` the supplied `json_body`. Classic Python, `in` works for `dict` or `str` but `json_body["error"]` will only work if `json_body` is a `dict`.
This is the minimal fix to now throw KeyError and let the unparsed json_body + message bubble up in the OpenAIError.

Handle OpenAIErrors created with 'str' json_body

---

openai/cli.py

Fix https://github.com/openai/openai-python/issues/283.

CLI: Fix missing max_tokens arg of chat_completions.create

---

chatml.md

I have a few suggested changes for `chatml.md`:
1. `Note this format...` -> `However, this format...` (alternatively, `Note that this format...`). 
2. `...similar to a SQL injections` -> `...similar to SQL injections`.

Fix a couple of grammar mistakes in chatml.md

---

openai/api_requestor.py

By default, the Requests library use the proxy settings from the environment variable HTTPS_PROXY. It has higher priority than the "proxies" setting in the session, which may lead to confusing behaviors if both environment variables and the "openai.proxy" config are set. This patch explicitly informs the Requests library to use the "openai.proxy" config when generating requests.

openai.proxy settings should override env var HTTPS_PROXY

---

openai/cli.py

The Azure API need to pass parameter `engine`. Follow the pattern `Completion.create` to make `model` optional and add `engine` as a parameter too.
Tested on Azure OpenAI API passed with
```
openapi api chat_completions.create -e chatgpt -g user "hello"
```

[Azure] CLI: Add support for azure openai chat completion API

---

README.md
openai/_openai_scripts.py

Due to the fact that the openai cli cannot function properly in some poor network environments without a proxy, add a '--proxy' parameter to overcome this difficulty.
v1. support "--proxy" parameter.
v2. give proxy example in README.
v3. supports using multiple "--proxy" parameters.

Add proxy argument support for openai client

---

openai/validators.py

* add case to handle indented .json parsing
* Fix formatting
---------

add case to handle indented .json parsing (#175)

---

openai/datalib/__init__.py
openai/datalib/common.py

Fixes #403
```dockerfile
FROM python:3.8
RUN pip install git+https://github.com/harupy/openai-python.git@add-init.py
RUN python -c 'from openai.api_resources.embedding import Embedding'
```
works fine now

Add `openai/datalib/__init__.py`

---

openai/util.py

addressing the issue https://github.com/openai/openai-python/issues/393#issue-1666480640
just changed the link for OpenAi  API
before: https://onboard.openai.com
after: https://platform.openai.com/account/api-keys

updated the link for OpenAI API

---

openai/embeddings_utils.py

The embedding utility functions currently only accept a minimum number of arguments. If a user needs to specify a few more keywords, that person can no longer use these functions, making them less useful than they could be. An example is shown in #392, in which an extra `request_timeout` argument can help bypass an unresolved bug.
This PR solves this problem by adding `kwargs` to all these utility functions.

Pass in keyword arguments in embedding utility functions

---

openai/__init__.py

Adds the `OPENAI_API_VERSION` environment variable so this can be configured while using the CLI.

allow api_version to be set by environment variable

---

openai/cli.py

Streamed chat completions use a different response structure vs non-streamed, i.e. deltas, which caused KeyError exceptions. Also these token deltas may have roles, and there may be empty deltas at the end of a completion. Handle these cases sensibly without breaking the non-streamed path. 
I manually tested both the streamed and non-streamed paths, but no unit tests, sorry, was busy.

Fixed CLI streamed chat completions.

---

README.md

As chat models are now most popular, updates the README to make `ChatCompletions` the suggested integration path.

Update README to use gpt-3.5-turbo by default

---

README.md
openai/__init__.py

This PR bumps the references to the latest Azure OpenAI API version.

Updating code and readme to reference the Azure's newest 2023-05-15 API Version

---

openai/api_requestor.py
openai/openai_object.py
openai/tests/test_api_requestor.py
openai/tests/test_util.py

This PR fixes https://github.com/openai/openai-python/issues/140 by forcing open `Session`s to be closed periodically (every 3 minutes at most). This PR also changes the rendering of API responses to maintain the sorting provided by the backend.

Periodically close open `request.Sessions` to avoid buggy interaction with Docker Desktop

---

openai/api_resources/chat_completion.py

Update docstring in chat_completion API resource

---

README.md

- Add newer completions models
- Remove mention of older models
- Fix links to old beta page

Update README.md to show newer completions models

---

README.md

Add in code examples for Python SDK that are relevant for fine-tuning

Update README.md with fine-tuning examples

---

openai/api_requestor.py

This commit updates the SSE parser to handle cases where there is an optional space after the "data:" prefix. Described in detail here - https://github.com/openai/openai-python/issues/498
To address this, I modified the parser code to use the startswith method and then strip any leading or trailing whitespaces from the line. This ensures that the parser can handle both cases where there is a space after "data:" and where there isn't. The modified code now correctly decodes the line as UTF-8 and returns the parsed data.
This change improves compatibility with different SSE implementations and ensures that the parser functions correctly in various scenarios. It provides a more flexible solution that aligns with the SSE specification and accommodates libraries like springframework that omit …

Fix: SSE Stream parser expects additional space after colon "data:"

---

openai/api_requestor.py

Currently the `aiohttp.ClientResponse` objects are never closed, which might be problem for long-running sessions, with streaming. Since users might not consume the whole stream, the request object is never released and the hope is that the session close will release it. However it's possible to supply a long-running session which is not closed when the request ends. I thus added a code which will release/close the responses.
Relates issues: https://github.com/openai/openai-python/issues/570
The aiohttp.session management is done using `@asynccontextmanager` (see https://github.com/openai/openai-python/blob/main/openai/api_requestor.py#L771-L778) . This is problematic because it creates an async generator. Let's see why.  Given the following code:
```
import asyncio
import os
from …
```

🐛 fixed asyncio streaming bugs

---

openai/api_resources/abstract/engine_api_resource.py

I was testing some code and I got this error:
```
File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 37, in class_url
raise error.InvalidRequestError(
TypeError: InvalidRequestError.__init__() missing 1 required positional argument: 'param'
```
So I checked this file and saw that in a few cases, InvalidRequestError was missing the second positional argument `param`

Bugfix: Add param positional arg to InvalidRequestError

---

README.md

The README refers to engine parameter but as far as I am aware, that is deprecated in favor of `deployment_id`, plus the example uses `deployment_id`.

Replace engine with deployment_id in README

---

openai/embeddings_utils.py

Closes https://github.com/openai/openai-python/pull/495

Update embeddings_utils.py to set default model to text-embedding-ada-002

---

src/openai/cli/_api/audio.py

Fix for #333 
My case is using `openai api audio.transcriptions.create -f audio.mp3`. Without the fix the returned value is `Error: Error code: 400 - {'error': {'message': "Unrecognized file format. Supported formats: ['flac', 'm4a', 'mp3', 'mp4', 'mpeg', 'mpga', 'oga', 'ogg', 'wav', 'webm']", 'type': 'invalid_request_error', 'param': None, 'code': None}}`.
The issue was that using BufferReader to read from the audio file was not keeping the `name` attribute so the file detection code on the server side was failing.
My fix is a viable workaround but a more invasive fix would be better. I found numerous other posts with this kind of issue for a while :
- https://community.openai.com/t/has-the-whisper-error-been-solved/433315
- https://community.openai.com/t/whisper-api-cannot-read-files-cor …

fix(cli/audio): file format detection failing for whisper

---

README.md

The notebook link in the main README pointed an old directory.

docs(readme): fix broken azure_ad notebook link

---

src/openai/_types.py

Fix typo in docstring of _types.NotGiven

---

README.md

https://github.com/openai/openai-python/issues/692 
Updates Azure OpenAI with a note warning users that Dall-E is not supported in the v1 SDK yet.

Adds DALL-E note to Azure OpenAI in v1 SDK

---

examples/assistant.py

Implement [Assisants](https://platform.openai.com/docs/assistants/overview) code example

Add assistants example

---

pyproject.toml

Having the license classifier in PyPI is also important so that it is uploaded as part of the package's metadata. Otherwise, when querying it to PyPI this information is not shown in the package's metadata.

feat: add license classifier to PyPI package

---

src/openai/_utils/_utils.py
src/openai/lib/_validators.py
tests/test_required_args.py

changed concatenation to f-strings to improve readability and performance

chore(internal): replace string concatenation with f-strings

---

src/openai/_exceptions.py

Simply assign the body from the parameter to the class variable.
Based on the comment in the code:
```
""The API response body.
If the API responded with a valid JSON structure then this property will be the
decoded result.
If it isn't a valid JSON structure then this will be the raw response.
If there was no response associated with this error then it will be `None`.
"""
```
closes https://github.com/openai/openai-python/issues/948

fix(errors): properly assign APIError.body

---

src/openai/lib/azure.py

Identify returned "token" as string.
- Set function _get_azure_ad_token() return statement value type as `str`.
- Should fix CI / lint workflow

fix(types): make it clearer that _get_azure_ad_token() returns a str

---

README.md

docs(readme): improve some wording

---

src/openai/cli/_api/audio.py
src/openai/cli/_utils.py

- Modified the ``print_model` function in `openai/cli/_utils.py` to handle string responses appropriately.
- Added a type check in `print_model` to print the response directly if it is a string, avoiding the `model_dump_json` call.
Fixes #1035

fix(cli/audio): handle non-json response format

---

.stats.yml
src/openai/resources/beta/chat/completions.py
src/openai/resources/chat/completions.py
tests/api_resources/chat/test_completions.py

Should help prevent users from accidentally trying to use `chat.completions.create()` instead of `beta.chat.completions.parse()` for structured outputs auto parsing.

feat(client): raise helpful error message for response_format misuse

---

src/openai/lib/_pydantic.py
tests/lib/test_pydantic.py

Pydantic 2 introduced `$defs` and removed `definitions`. The latter is not handled during json parsing in "Structured Outputs" mode, so `additionalProperties: False` is not set and the request fails with pydantic<2 with nested objects in the schema, as they are not getting the flag set.
Added `definitions` in `_ensure_strict_json_schema` to correctly parse the schema with pydantic<2 and not fail on requests with nested objects.
Steps to reproduce the error:
openai==1.40.1
pydantic==1.10.12
```
from pydantic import BaseModel
from openai import OpenAI
client = OpenAI(api_key=OPENAI_API_KEY)
class Step(BaseModel):
explanation: str
output: str
class MathReasoning(BaseModel):
final_answer: str
step: list[Step]
completion = client.beta.chat.completions.parse(
model="gpt-4o-2024-08-06", …
```

fix(json schema): support recursive BaseModels in Pydantic v1

---

src/openai/cli/_tools/migrate.py

We moved the source for Grit binaries to GitHub, which meant the latest releases weren't available for patches to issues like https://github.com/openai/openai-python/issues/1647.
I have tested this on Mac and confirmed the right Linux URL.
- https://github.com/openai/openai-python/issues/1647
- https://github.com/getgrit/gritql/releases

fix(cli/migrate): change grit binaries download source

---

src/openai/lib/_pydantic.py
tests/lib/chat/test_completions.py
tests/lib/schema_types/query.py
tests/lib/test_pydantic.py

fixes one of the issues reported in https://github.com/openai/openai-python/issues/1659

fix(json schema): remove `None` defaults

---

src/openai/lib/_parsing/_completions.py
src/openai/lib/_pydantic.py
tests/lib/chat/test_completions.py

feat(parsing): add support for pydantic dataclasses

---

README.md

OPENAI_BASE_URL defaults to https://api.openai.com/v1, so if you add a replacement and forget to append the /v1, it will result in 404s. Let's give an example that ends in v1
https://github.com/openai/openai-python/blob/b2f58cba092cfb3083dc31de429fa19d89f739dc/src/openai/_client.py#L118C1-L121C52

docs(readme): improve custom `base_url` example

---

README.md

Add examples for calling the `completion` API with image content

docs(readme): add examples for chat with image content

---

src/openai/lib/streaming/_assistants.py

Disable warnings emitted from AssistantEventHandler. Warnings arise from differences in the Azure API and end up not being that helpful, nor configurable by the user.

chore(streaming): silence pydantic model_dump warnings

---

src/openai/_models.py
tests/lib/chat/_utils.py
tests/test_legacy_response.py
tests/test_response.py
tests/utils.py

Previously we'd print things like this
```py
ParsedChatCompletion[MathResponse](
id='chatcmpl-ABqjDEHcQeJS1zQKQsjk7pryPMOPl',
_request_id='req_8b371ab5485eea304486a17d9e210bcc',
__exclude_fields__={'__exclude_fields__', '_request_id'}
)
```
but we didn't intend for `_request_id` and `__exclude_fields__` to be printed, this PR fixes that

chore(pydantic v1): exclude specific properties when rich printing

---

helpers.md

Very minor fix to `helpers.md`.
cc @RobertCraigie

docs(helpers): fix chat completion anchor

---

helpers.md

There was a typo in thread's polling method name. Removed wrong extra letter in "..outputs.."

docs(helpers): fix method name typo

---

src/openai/_base_client.py

I know this is auto generated, thus this PR may serve as a hint to fix the upstream code-generator bug.
```
import logging
from openai import OpenAI, AsyncOpenAI
import openai
logging.basicConfig(level=logging.DEBUG,
format='%(asctime)s - %(levelname)s - %(filename)s:%(funcName)s:%(lineno)d - %(message)s',
datefmt='%Y-%m-%d %H:%M:%S')
client = OpenAI(api_key='dummy', base_url='https://localhost:1111') # deliberate not exist domain
client.chat.completions.create(messages=[], model='my-model')
client = AsyncOpenAI(api_key='dummy', base_url='https://localhost:1111') # deliberate not exist domain
await client.chat.completions.create(messages=[], model='my-model')
```
You can look at AsyncOpenAI vs OpenAI to see why this line of code is wrong. Or, look at a dozen line above this line to see …

fix(client/async): correctly retry in all cases

---

src/openai/lib/streaming/_assistants.py

docs(assistants): correct on_text_delta example

---

src/openai/lib/azure.py

Closes: https://github.com/openai/openai-python/issues/1894
Handle trailing slash
Example
https://github.com/openai/openai-python/blob/83f4774156dc3e29c7fe6be9ffd681df68534509/examples/azure.py#L29

fix(azure): handle trailing slash in `azure_endpoint`

---

src/openai/cli/_tools/migrate.py

Fixing `openai migrate` by updating renamed binaries.
Closes #1838
On Oct25, [gritql main CLI name was changed](https://github.com/getgrit/gritql/pull/564), introducing #1838.
Upon inspection of [the relevant commit](https://github.com/getgrit/gritql/pull/564/commits/b183b4ac64a6f6cbd4ba5e7a73af8301c2156fdc), it consisted of a renaming of the prefix or their binaries.
This PR renames the prefix according to their change.

fix(cli/migrate): change grit binaries prefix

---

README.md

Fixed grammar in the README so that the period is inside the parentheses instead of outside.
"(Please open a GitHub issue to let us know if you are relying on such internals.)"
https://www.masterclass.com/articles/period-inside-or-outside-parentheses

docs(readme): moved period to inside parentheses

---

examples/realtime/azure_realtime.py

Add a simple example that shows how to configure the Azure client to use Realtime API.

docs(examples/azure): example script with realtime API

---

src/openai/lib/_pydantic.py
tests/lib/test_pydantic.py

Fixes #2024 
This PR updates the `_ensure_strict_json_schema` function so that when a `$ref` is expanded inline (due to the presence of other fields like `description`), we recursively re-run the function on the resulting inline object. This ensures `additionalProperties: false` is correctly applied even if the schema is expanded.  
Additionally, new test code has been added to confirm that models with nested references and annotated fields (e.g., `Field(description="...")`) correctly produce `additionalProperties=False` for the inline-expanded objects.  
- This addresses scenarios where `$ref` plus extra properties leads to inline expansion, causing the prior implementation to skip setting `additionalProperties: false`.  
- The newly introduced unit test verifies that models with …

fix(structured outputs): correct schema coercion for inline ref expansion

---

src/openai/resources/chat/chat.py

docs: fix typo

---

README.md
helpers.md

docs(readme): navigate section links

---

src/openai/cli/_api/chat/completions.py

fix(cli/chat): only send params when set

---

examples/audio.py
examples/speech_to_text.py
examples/text_to_speech.py
pyproject.toml
requirements-dev.lock
requirements.lock
src/openai/helpers.py
src/openai/lib/helpers/__init__.py
src/openai/lib/helpers/local_audio_player.py
src/openai/lib/helpers/microphone.py

feat(helpers): add helpers for local audio testing

---

src/openai/lib/streaming/chat/_completions.py

…ng `from_json`
- add filter logic to ensure chunk streaming work properly.
- I notice that in some case, when messages stack around 2 - 3 conversation turn, it will throw 'EOF error parsing', so I launch quick check on client lib, and found that, in some use case, server will send empty string with '\n', so it make jiter parsing function error.

fix(parsing): handle whitespace only strings

---

src/openai/_utils/_proxy.py
tests/test_utils/test_proxy.py

Fix #2056
I assume this might need to be upstreamed in Stainless then?

fix: ignore errors in isinstance() calls on LazyProxy subclasses

---

src/openai/lib/azure.py

Adding /images/edits as route that requires a deployment

fix(azure): mark images/edits as a deployment endpoint

---

pyproject.toml
requirements-dev.lock
requirements.lock
tests/lib/chat/test_completions_streaming.py
tests/lib/snapshots.py
tests/lib/utils.py

Bumps the version of [inline-snapshot](https://15r10nk.github.io/inline-snapshot/latest/) used for testing, and removes the custom function that was added to its public API.

chore: bump `inline-snapshot` version to 0.28.0
