openai/openai-python

openai/upload_progress.py
openai/version.py

* Have progress meter actually reach 100%
* version number

Have progress meter actually reach 100% (#14)

---

openai/version.py
setup.py

* Add `tqdm` requirement
* Version bump

Add `tqdm` requirement (#15)

---

openai/cli.py
openai/object_classes.py

* Add `deployments.list`,  `deployments.get`, `deployments.delete` and `deployments.create` commands to manage deployments for azure endpoints
To use the CLI with azure endpoints:
```bash
export OPENAI_API_BASE="..."
export OPENAI_API_TYPE="azure"
export OPENAI_API_KEY="..."
```

[Azure] Add "deployments.*" commands to the CLI

---

openai/api_requestor.py

Fixes https://github.com/openai/openai-python/issues/141
Co-authored-by: andrewpeng@openai.com <Andrew Peng>

Change request logs to debug level

---

chatml.md

Changed "much most" to "much more"

Typo, line 93

---

chatml.md

Fixed a tiny typo in chatml.md (iteract -> interact)

---

chatml.md

just a minor fix:
```
ChatML documents consists -> ChatML documents consist 
```
have a nice weekend:)

fixed a minor typo in chatml.md

---

openai/__init__.py

Adds `__version__` in `__init__.py`.

Add `__version__` in `__init__.py`

---

openai/api_requestor.py

The current code doesn't actually type check and has the potential to raise a TypeError (trying to do something like 'str' in None).

Fix grabbing value out of header

---

openai/api_resources/file.py
openai/cli.py

This PR adds a CLI for the `FineTuningJobs` SDK, under the `openai api fine_tuning.jobs` interface. This interface closely matches that of the original `openai api fine-tunes`, allowing users to create, retrieve, list, and cancel fine tuning jobs.

[fine_tuning] Add CLI for fine_tuning.jobs

---

openai/api_resources/abstract/nested_resource_class_methods.py
openai/cli.py

This PR fixes pagination for the `FineTuningJob.list_events` method

[fine_tuning] fix pagination for auto-generated list_events (#188)

---

README.md

Closes: https://github.com/openai/openai-python/issues/596

Update README.md to fix the fine-tuning model delete example

---

README.md

Update pointer to Jupyter notebooks as finetuning doesn't exist

---

src/openai/lib/azure.py

Add images/generations to azure endpoints list.

add images/generations to azure endpoints list

---

src/openai/_models.py

docs: fix code comment typo

---

README.md

Revert #766 now that it's no longer relevant

Remove DALL-E note

---

src/openai/_utils/_proxy.py

chore: fix typo

---

src/openai/lib/_pydantic.py
tests/lib/chat/test_completions.py
tests/lib/test_pydantic.py

https://community.openai.com/t/structured-response-enums-not-supported-in-with-pydantic-schema-generation/901973/4?u=foxalabs

fix(json schema): handle field descriptions with $refs

---

README.md

Changes made to solve issue #1825
Fixing by adding the import

docs(readme): add missing asyncio import

---

.github/workflows/ci.yml
pyproject.toml
src/openai/_extras/__init__.py
src/openai/_extras/numpy_proxy.py
src/openai/_extras/sounddevice_proxy.py
src/openai/helpers/local_audio_player.py
src/openai/helpers/microphone.py

closes #2238
to use the audio helpers you must now
```
pip install openai[audio]
```

fix(package): make sounddevice and numpy optional dependencies

---

examples/realtime/push_to_talk_app.py

portaud and ffmpeg both need to be installed in order for the pursh_to_talk_app example to run.

docs(examples/realtime): mention macOS requirements
